### PR TITLE
optional simplification of presence condtions after parsing

### PR DESCRIPTION
**Pull request by alexrhein**
had to make Opt.condition and Choice.condition modifiable (var instead of val) to simplify the conditions
Options: --bdd --simplifyPresenceConditions

### CODE REVIEW

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Could you please rewrite the code without making Choice mutable?

Instead of changing a field of a choice, please create a new choice with the changed conditions. I would like to keep working with immutable data structures and it is quite dangerous if somebody decides to change the condition of a choice without preserving the invariants that you consider here.

**Comment by alexrhein** [comment]
I tried to.
Making a new Choice/Opt with the changed condition is not difficult.
The problem is that the old choice object is part of a Product p.
I would have to replace the old Choice in p.productElement(i) with my
new Choice.
It seems that Product does not support setting/replacing elements.
And the real type of p might be any AST class...

Am 01/15/2015 um 05:59 PM schrieb Christian Kästner:

**Comment by ckaestne** [comment]
Yes, by changing a part of an immutable data structure you have to reconstruct all parent elements. Doing this generically is a bit trickier, but doable. Kiama has an infrastructure for that, for example as used in de.fosd.typechef.crewrite.ProductDerivation

**Comment by alexrhein** [comment]
The tests failing in TravicCI are 
[info] - linuxtestflock_c - differential testing *** FAILED ***
[info] - elifchain_c - differential testing *** FAILED ***
[info] - byteorder_h - differential testing *** FAILED ***

They do not fail on my machine.
I looked into it, but I can't think of a reason why they could fail. 
My changes have no effect unless options --bdd --simplifyPresenceConditions are active.

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Ignore those test cases. I'm not sure why they fail on travis, there seems to be some randomness in the process. It works fine locally and on my Jenkins box.

**Comment by ckaestne** [comment]
Thanks. Looks good!

**Pull request merged**
