### PR TITLE
adds check to avoid duplicate inclusion in the preprocessor #38

### PR DESCRIPTION
**Pull request by szabta89**
Maintains a map of files to conditions, where the value represents the condition under which the file was already included. Include a file in the preprocessor only if it was not included under the given condition.

### CODE REVIEW

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by szabta89** [comment]
I have referenced the wrong issue in the commit message, but the title here refers to the correct issue.

**Comment by ckaestne** [comment]
great, thanks!

**Comment by ckaestne** [comment]
closes #38

**Pull request merged**
