### PR TITLE
--dimacsFeaturePrefix command-line option

### PR DESCRIPTION
**Pull request by clhunsen**
The option ``--dimacsFeaturePrefix`` was advertised in ``--help``, but was not parsed in the end. Hence, the user was stuck with the default value ``CONFIG_``.

I implemented a defensive parsing of the option in the frontend to ensure a proper loading of the feature model.

### CODE REVIEW

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by ckaestne** [comment]
Can one of the admins verify this patch?

**Comment by clhunsen** [comment]
I guess you did not mean me with that comment. Is there any progress somehow to be expected?

**Comment by ckaestne** [comment]
Thanks for the patch!

I did not see the original notification and the "Can one of ..." is an autogenerated message by Github.

**Comment by clhunsen** [comment]
You are welcome, thanks for merging.

**Pull request merged**
